nelmio_api_doc:
  documentation:
    info:
      title: Hiberus technical test
      description: API REST for product and order management
      version: 1.0.0
  areas:
    path_patterns:
      - ^/api(?!/doc)
